### ISSUE TITLE
Unable to deploy stream via Dashboard

### ISSUE THREAD

**Issue by TomaszGaweda** [spring-cloud/spring-cloud-dataflow-ui#1016]
Hi,

I'm trying to deploy very simple stream, but it's not possible from UI.
I'm working on Spring DataFlow 2.0.0.BUILD-SNAPSHOT (version from today),

When trying to deploy stream, UI is asking for `/info` endpoint, then it fails on UI side with error:
```
ERROR TypeError: "u.getMessage is not a function"
	zUnb/NZ</n.prototype.ngOnInit/this.config$< http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:3173467
	error http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:529750
	_error http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:964353
	error http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:964059
	notifyError http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:1015513
	_error http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:1761532
	error http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:964059
	_next http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:517503
	next http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:963979
	_next http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:964296
	next http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:963979
	_next http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:517529
	next http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:963979
	_next http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:517529
	next http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:963979
	_next http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:1129833
	next http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:963979
	notifyNext http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:1718396
	_next http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:1761424
	next http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:963979
	d http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:1820397
	invokeTask http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:8475
	onInvokeTask http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:686258
	invokeTask http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:8388
	runTask http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:3651
	invokeTask http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:9569
	y http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:20495
	b http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:20727
main.011d1939833b5a404abf.js:1:674475
nb
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:674475
CcnG/ub</n.prototype.handleError
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:674701
next
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:693054
CcnG/rc</u.prototype.subscribe/f<
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:652881
FFOo/s</u.prototype.__tryOrUnsub
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:966152
FFOo/s</u.prototype.next
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:965294
FFOo/c</u.prototype._next
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:964296
FFOo/c</u.prototype.next
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:963979
K9Ia/s</u.prototype.next
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:1002899
CcnG/rc</u.prototype.emit
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:652647
onHandleError/<
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:686656
0TWp/</</u</t.prototype.invoke
http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:7800
0TWp/</</o</n.prototype.run
http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:2960
CcnG/kb</n.prototype.runOutsideAngular
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:687365
onHandleError
http://localhost:9393/dashboard/main.011d1939833b5a404abf.js:1:686618
0TWp/</</u</t.prototype.handleError
http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:7880
0TWp/</</o</n.prototype.runTask
http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:3705
0TWp/</</c</n.invokeTask
http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:9569
n/this.invoke<
http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:9454
u/e.args[0]
http://localhost:9393/dashboard/polyfills.dca0a98914a4691e4ece.js:1:24757
```

It's probably related to this issue's comment: #580. However, in SCDF >= 2.0, Skipper is necessary AFAIK, so deployment would not be possible at all via UI

**Comment by sabbyanandan** [comment]
Hi, @TomaszGaweda. Thank you for reporting this. This is indeed a bug - a blocker in fact. We will rectify it asap. Please use the Shell/REST-APIs to deploy the streams in the meantime.

**Comment by ghillert** [comment]
This issue was caused by the fix for https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/985

**Comment by sabbyanandan** [comment]
@TomaszGaweda: Now that we have resolved this problem, feel free to pull the latest SNAPSHOT build, and try it out. Let us know if you see any other anomaly.

**Comment by jfleck1** [comment]
Can we get a fresh 2.0.0.BUILD-SNAPSHOT deployed to docker hub? Specifically;
https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server-kubernetes

**Comment by sabbyanandan** [comment]
Hi, @TomaszGaweda. In 2.0, we have consolidated Local, CF and K8s-server responsibilities in a single-server (same binary/image). The single-server packs all the 3 deployer libraries in it, so there's only one image going forward (see: [2.0 M1 blog](https://spring.io/blog/2018/12/21/spring-cloud-data-flow-and-skipper-2-0-m1-released#single-server-that-runs-on-all-supported-platforms)).

You'd use https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server going forward. We will confirm to make sure the `latest` tag is pushed with all the upstream commits via spring-cloud/spring-cloud-dataflow#2758.

Going forward, if you have questions like this, please ping us on Gitter.
